### ISSUE TITLE
default values for /add

### ISSUE THREAD

**Issue by alor** [yhdelgado/django-notifications-rest#1]
when using the /add endpoint you must specify all the fields otherwise you'll get this error: 

{"level":["This field is required."],"description":["This field is required."],"unread":["This field is required."],"public":["This field is required."],"deleted":["This field is required."],"emailed":["This field is required."]}

those fields have defaults. they should be used if not specified.

**Comment by PetrDlouhy** [comment]
This should be fixed now in `master`, I will make the release as soon as I got the permissions.
