### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by PetrDlouhy** [yhdelgado/django-notifications-rest#12]
@yhdelgado I would like to make a new release. Would you please give me rights to PyPI repository? My PyPI username is `petr.dlouhy`.

**Comment by yhdelgado** [comment]
> @yhdelgado I would like to make a new release. Would you please give me rights to PyPI repository? My PyPI username is `petr.dlouhy`.

Done!

**Comment by PetrDlouhy** [comment]
@yhdelgado Thank you very much. The new release is now live.

**Comment by yhdelgado** [comment]
> @yhdelgado Thank you very much. The new release is now live.

Well done!
